server:
  port: 8084

spring:
  zipkin:
    base-url: ${ZIPKIN:http://10.96.0.13:9411/}
  sleuth:
    sampler:
      probability: ${SAMPLER_PROBABILITY:1.0}
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      httpclient:
        pool:
          max-connections: ${MAX_CONNECTIONS:300}
        connect-timeout: ${CONNECT_TIMEOUT:10000}
        response-timeout: ${RESPONSE_TIMEOUT:5s}
      metrics:
        enabled: true
      default-filters:
        - StripPrefix=1
        - name: Retry
          args:
            retries: 3
            series:
            - SERVER_ERROR
            - CLIENT_ERROR
            statuses:
            - INTERNAL_SERVER_ERROR
            methods:
            - GET
            - POST
            exceptions:
            - java.io.IOException
            - java.util.concurrent.TimeoutException
  application:
    name: demo-gateway


ribbon:
  okhttp:
    enabled: true
  eager-load:
    enabled: true


logging:
  logPath: /var/log/${spring.application.name}
  level:
    com.netflix.discovery.shared.resolver.aws: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
